version: 2.1

orbs:
  node: circleci/node@1.0.1

workflows:
  version: 2
  eslint-config:
    jobs:
      - build-eslint-config

jobs:
  build-eslint-config:
    docker:
      - image: node@10
    steps:
      - checkout
      - run:
          name: Change workdir
          command: cd packages/eslint-config
      - restore_cache:
          key: dependency-cache-{{ checksum "packages/eslint-config/package.json" }}
      - run:
          name: Yarn Install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "packages/eslint-config/package.json" }}
          paths:
            - packages/eslint-config/node_modules
      - run:
          name: Test
          command: yarn test
